### ISSUE TITLE
About DSEC-MOD dataset

### ISSUE THREAD

**Issue by rwn17** [ZZY-Zhou/RENet#1]
Thanks for your excellent work, and congratulations on the acceptance! 

I was wondering whether DSEC-MOD annotates objects that can potentially move, including still cars and pedestrians, or objects that are actually moving. I have this question because, in the paper, it said annotations are from auto-annotate of detection2 and didn't illustrate how you figure out whether one object is moving or not.

Cheers,
Weining

**Comment by ZZY-Zhou** [comment]
Hello Weining,

Thank you for your interest in our work, and also your question.

DSEC-MOD, as its name illustrates, concentrates only on moving objects. In other words, basically, the annotations do not include still objects; and this part is verified manually after the auto-annotation, as mentioned shortly in the paper. However, there do exist some subtle cases such as a person turning around then walking, or a car pausing very shortly at a crossing, etc; we are going through all these.

Since we do believe in the interest and the importance of Moving Object Detection (MOD) in Autonomous Driving and other fields, we are planning to work further on this DSEC-MOD dataset.
You are more than welcome to discuss with us about the annotations, on subtle cases or others, when we release DSEC-MOD.

Best,
Zhuyun
